/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormStudent: typeof import('./components/student/FormStudent.vue')['default']
    Header: typeof import('./components/layouts/Header.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
  }
}
