/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/estudante/[id]/editar': RouteRecordInfo<'/estudante/[id]/editar', '/estudante/:id/editar', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/estudante/cadastro': RouteRecordInfo<'/estudante/cadastro', '/estudante/cadastro', Record<never, never>, Record<never, never>>,
    '/estudantes/': RouteRecordInfo<'/estudantes/', '/estudantes', Record<never, never>, Record<never, never>>,
  }
}
